### ISSUE TITLE
New build of HASS

### ISSUE THREAD

**Issue by basbl** [hedlund/rpi-hass#1]
Hi @hedlund,

Could you create a new build of the image with the latest version of hass? If you'd like I could send in a PR.

Thanks in advance!

**Comment by hedlund** [comment]
Hi @basbl ,
Sorry that I haven't been more active in updating the image. It's been on my TODO-list for a while now, but I just haven't done it..

I just pushed a new build to the Docker hub with the tag 0.36.1. I didn't tag it as latest, as I haven't tested it myself yet, but if you want to try it I'd love to hear back if it works.

It's a straight version bump to 0.36.1, using the same configuration as the old version. I can see that the official Docker image has included some extra stuff for libcec amongst other things, but I haven't added those in here (yet), so that might be a deal breaker..

**Comment by basbl** [comment]
Thanks a lot @hedlund! No problems, I'm grateful that you've responded this quickly.

I'll check out the new build today and I'll let you know about any issues that I encounter.

**Comment by basbl** [comment]
Updated and works great 👍
